#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $ALEX_REPO == "Alex-UserBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RocnViYW1veS9BbGV4LS11YkFkZG9ucy9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $ALEX_REPO == "Alex-UserBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RocnViYW1veS9BbGV4LS11YkFkZG9ucy9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $LEGEND_REPO =~ $regex ]]
    then
        if [[ $LEGEND_REPO_BRANCH ]]
        then
            echo "${Alex_REPO}/archive/${Alex_REPO_BRANCH}.zip"
        else
            echo "${Alex_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RocnViYW1veS9BbGV4LS11YkFkZG9ucy9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Alex-winning.zip"
    echo "  ⚜Downloading Alexbot V-0.1Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    AlexPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  AlexBot V-0.1 Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $AlexPATH
    echo "    • Starting Alex V-0.1•    "
    echo "
    AlexBot
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
